Presentation/Models/PaySlipViewModel.cs
namespace Presentation.Models
{
    public class PaySlipViewModel
    {
        public int SelectedAppUserId { get; set; }
        public string? FullName { get; set; }
        public decimal Awards { get; set; }
    }
}

Presentation/Controllers/PaySlipController.cs
using Business.Abstract;
using DataAccess.Concrete.Context;
using Entities.Concrete;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Presentation.Models;
using SkiaSharp;
using System.Data;
using System.Security.Claims;
using System.Text;

namespace Presentation.Controllers
{
    public class PaySlipController : Controller
    {
        private readonly IPaySlipService _paySlipService;
        private readonly UserManager<AppUser> _userManager;
        private readonly HRMSContext _hrmsContext;

        public PaySlipController(IPaySlipService paySlipService, UserManager<AppUser> userManager, HRMSContext hrmsContext)
        {
            _paySlipService = paySlipService;
            _userManager = userManager;
            _hrmsContext = hrmsContext;
        }

        public IActionResult Index()
        {
            var paySlips = _hrmsContext.PaySlips.Include(p => p.AppUser).ToList();
            var appUserNames = paySlips.Select(p => p.AppUser.FullName).Distinct().ToList();
            var appUserSalary = paySlips.Select(p => p.AppUser.Salary).Distinct().ToList();
            var selectList = new SelectList(appUserNames);
            var selectListSalary = new SelectList(appUserSalary);
            ViewBag.AppUserNames = selectList;

            return View(paySlips);
        }

        [HttpGet]
        public IActionResult Index(string selectedAppUser, DateTime? startDate, DateTime? endDate)
        {
            var paySlips = _hrmsContext.PaySlips.Include(p => p.AppUser).ToList();

            if (!string.IsNullOrEmpty(selectedAppUser) && selectedAppUser != "Personeller")
            {
                paySlips = paySlips.Where(p => p.AppUser.FullName == selectedAppUser).ToList();
            }
            if (startDate.HasValue && endDate.HasValue)
            {
                paySlips = paySlips.Where(p => p.CreatedTime >= startDate && p.CreatedTime <= endDate).ToList();
            }

            var appUserNames = _hrmsContext.Users.Select(u => u.FullName).Distinct().ToList();
            var selectList = new SelectList(appUserNames);

            // Toplam Ücret Hesaplama
            decimal? usersTotalSalary = _hrmsContext.Users.Sum(u => u.Salary);
            decimal payslipTotalAwards = paySlips.Sum(p => p.Awards);

            ViewBag.AppUserNames = selectList;
            return View("Index", paySlips);
        }
        public ActionResult AddPaySlip()
        {
            var appUsers = _userManager.Users.ToList();
            ViewBag.AppUsers = new SelectList(appUsers, "Id", "FullName");

            return View();
        }

        [HttpPost]
        public ActionResult AddPaySlip(PaySlip model)
        {
            if (ModelState.IsValid)
            {
                _hrmsContext.PaySlips.Add(model);
                _hrmsContext.SaveChanges();

                return RedirectToAction("Index");
            }

            var appUsers = _userManager.Users.ToList();
            ViewBag.AppUsers = new SelectList(appUsers, "Id", "FullName");

            return View(model);

        }
        public IActionResult DeletePaySlip(int id)
        {
            var value = _paySlipService.GetById(id);
            _paySlipService.Delete(value);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult UpdatePaySlip(int id)
        {
            var paySlip = _hrmsContext.PaySlips.Find(id);

            if (paySlip == null)
            {
                return NotFound();
            }

            var appUsers = _userManager.Users.ToList();
            ViewBag.AppUsers = new SelectList(appUsers, "Id", "FullName");

            return View(paySlip);
        }
        [HttpPost]
        public ActionResult UpdatePaySlip(int id, PaySlip model)
        {
            if (ModelState.IsValid)
            {
                var paySlip = _hrmsContext.PaySlips.Find(id);

                if (paySlip == null)
                {
                    return NotFound();
                }

                paySlip.AppUserId = model.AppUserId;
                paySlip.Awards = model.Awards;

                _hrmsContext.SaveChanges();

                return RedirectToAction("Index");
            }

            var appUsers = _userManager.Users.ToList();
            ViewBag.AppUsers = new SelectList(appUsers, "Id", "FullName");

            return View(model);
        }

        public ActionResult DownloadAllPaySlips()
        {
            var paySlips = _hrmsContext.PaySlips.Include(p => p.AppUser).ToList();
            string logoImagePath = "C:\\Users\\sdoqa\\OneDrive\\Masaüstü\\Repos\\Miltek\\HRMS\\HRMS\\7533464.png";

            iTextSharp.text.Image logoImage = iTextSharp.text.Image.GetInstance(logoImagePath);
            logoImage.Alignment = iTextSharp.text.Image.ALIGN_LEFT; // Logoyu solo hizala
            logoImage.ScaleAbsolute(80, 100); // Logo boyutunu ayarla

            // PDF belgesini oluştur ve içeriğini ekle
            var document = new Document();
            using (MemoryStream memoryStream = new MemoryStream())
            {
                PdfWriter writer = PdfWriter.GetInstance(document, memoryStream);

                document.Open();

                // Logo görüntüsünü ekle
                document.Add(logoImage);


                BaseFont baseFont = BaseFont.CreateFont("c:\\windows\\fonts\\arial.ttf", BaseFont.IDENTITY_H, BaseFont.NOT_EMBEDDED);
                Font titleFont = new Font(baseFont, 12, Font.BOLD, BaseColor.Black);
                Font cellFont = new Font(baseFont, 11, Font.NORMAL, BaseColor.Black);


                // Şirket Bilgileri
                string companyInfo = "Şirket Adı: HRMS Friends Şirketi                                                    Vergi Dairesi: Ankara Vergi Dairesi\n" +
                                     "Adres: \tAnkamoll Mah. KazımKarabekir Cad. No:12                                     Vergi No: 1234567890\r\nMerkez / ANKARA\n" +
                                     "Telefon: 123-456-7890\n";
                document.Add(new Paragraph(companyInfo, cellFont));

                // Çizgi Ayırma


                document.Add(new Paragraph(" "));
                document.Add(new Paragraph("Bordro Raporu", titleFont));
                document.Add(new Paragraph(" "));

                PdfPTable table = new PdfPTable(5);
                table.WidthPercentage = 100;
                table.DefaultCell.Border = Rectangle.NO_BORDER; // Kenarlık olmadan hücreleri ayarla

                float[] columnWidths = { 3f, 2f, 2f, 2f, 3f };
                table.SetWidths(columnWidths);

                string[] headers = { "Personel Adı", "Prim Ödeme", "Maaş", "Toplam Ücret", "Tarih" };
                foreach (var header in headers)
                {
                    PdfPCell headerCell = new PdfPCell(new Phrase(header, cellFont));
                    headerCell.BackgroundColor = BaseColor.LightGray;
                    headerCell.HorizontalAlignment = Element.ALIGN_LEFT; // Başlıkları sola dayalı hale getir
                    headerCell.Border = Rectangle.NO_BORDER; // Kenarlık olmadan hücreleri ayarla
                    table.AddCell(headerCell);
                }

                bool isGrayRow = false;
                foreach (var paySlip in paySlips)
                {
                    PdfPCell cell = new PdfPCell(new Phrase(paySlip.AppUser.FullName, cellFont));
                    cell.FixedHeight = 20f; // Hücre yüksekliği 20 birim olarak ayarla
                                            // Gri arka plan rengini ayarla
                    if (isGrayRow)
                    {
                        cell.BackgroundColor = BaseColor.LightGray;
                    }
                    cell.Border = Rectangle.NO_BORDER; // Kenarlık olmadan hücreleri ayarla
                    table.AddCell(cell);

                    PdfPCell awardsCell = new PdfPCell(new Phrase(paySlip.Awards.ToString(), cellFont));
                    awardsCell.BackgroundColor = isGrayRow ? BaseColor.LightGray : BaseColor.White;
                    awardsCell.Border = Rectangle.NO_BORDER; // Kenarlık olmadan hücreleri ayarla
                    cell.FixedHeight = 20f;
                    table.AddCell(awardsCell);

                    PdfPCell salaryCell = new PdfPCell(new Phrase(paySlip.AppUser.Salary.ToString(), cellFont));
                    salaryCell.BackgroundColor = isGrayRow ? BaseColor.LightGray : BaseColor.White;
                    salaryCell.Border = Rectangle.NO_BORDER; // Kenarlık olmadan hücreleri ayarla
                    cell.FixedHeight = 20f;
                    table.AddCell(salaryCell);

                    PdfPCell totalCell = new PdfPCell(new Phrase((paySlip.Awards + paySlip.AppUser.Salary).ToString(), cellFont));
                    totalCell.BackgroundColor = isGrayRow ? BaseColor.LightGray : BaseColor.White;
                    totalCell.Border = Rectangle.NO_BORDER; // Kenarlık olmadan hücreleri ayarla
                    cell.FixedHeight = 20f;
                    table.AddCell(totalCell);

                    PdfPCell dateCell1 = new PdfPCell(new Phrase(paySlip.CreatedTime.ToShortDateString(), cellFont));
                    dateCell1.BackgroundColor = isGrayRow ? BaseColor.LightGray : BaseColor.White;
                    dateCell1.Border = Rectangle.NO_BORDER; // Kenarlık olmadan hücreleri ayarla
                    cell.FixedHeight = 20f;
                    table.AddCell(dateCell1);

                    isGrayRow = !isGrayRow;
                }

                document.Add(table);

                string companySignature = "              HRMS Friends Şirketi\n " +"Ad Soyad\n " +"İMZA";
                Chunk signatureChunk = new Chunk(companySignature, cellFont);

Presentation/Views/PaySlip/AddPaySlip.cshtml
@model Entities.Concrete.PaySlip
@{
    Layout = "~/Views/Shared/_AdminTemplateLayout.cshtml";
    ViewBag.Title = "Bordro Paneli";
}



<h2>Bordro Paneli</h2>

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(model => model.AppUserId, "Personel")
        @Html.DropDownListFor(model => model.AppUserId, (SelectList)ViewBag.AppUsers, "Personel Listele", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.AppUserId, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Awards)
        @Html.TextBoxFor(model => model.Awards, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Awards, "", new { @class = "text-danger" })
    </div>

    <button type="submit" class="btn btn-primary">Yeni Ücret Ekle</button>
}

Presentation/Views/PaySlip/Index.cshtml
@model List<Entities.Concrete.PaySlip>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminTemplateLayout.cshtml";
    ViewBag.Title = "PaySlips";
}



<div class="container">
    @using (Html.BeginForm("Index", "PaySlip", FormMethod.Get))
    {
        @Html.DropDownList("selectedAppUser", (SelectList)ViewBag.AppUserNames, "Personeller", new { @class = "form-control" })
        <br />
        <label for="startDate">Başlangıç Tarihi:</label>
        <input type="date" id="startDate" name="startDate" class="form-control">
        <br />
        <label for="endDate">Bitiş Tarihi:</label>
        <input type="date" id="endDate" name="endDate" class="form-control">
        <br />
        <button class="btn btn-info" type="submit">Filtrele</button>
    }
    <br /><br />
    <table class="table table-bordered">
        <tr>
            <th>#</th>
            <th>Personel Adı</th>
            <th>Maaş Prim</th>
            <th>Maaş</th>
            <th>Toplam Ücret</th>
            <th>Tarih</th>
            <th>Sil</th>
            <th>Güncelle</th>
            <th>Bordro indir</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.AppUser.FullName</td>
                <td>@item.Awards</td>
                <td>@item.AppUser.Salary</td>
                <td>@(item.Awards+item.AppUser.Salary)</td>
                <td>@item.CreatedTime</td>
                <td><a href="/PaySlip/DeletePaySlip/@item.Id" class="btn btn-danger">Sil</a></td>
                <td><a href="/PaySlip/UpdatePaySlip/@item.Id" class="btn btn-success">Güncelle</a></td>
                <td><a href="@Url.Action("DownloadDataAsPdfID", "PaySlip", new { id = item.Id })" class="btn btn-primary">Bordro İndir</a></td>
            </tr>
        }
    </table>
    <br />
    <br />
    <a href="@Url.Action("DownloadAllPaySlips", "PaySlip")" class="btn btn-primary">Bordroları İndir</a>
</div>

Presentation/Views/PaySlip/MyPaySlips.cshtml
@model List<Entities.Concrete.PaySlip>
@{
    ViewData["Title"] = "MyPaySlips";
    Layout = "~/Views/Shared/_AdminTemplateLayout.cshtml";
}


<div>
    <h3>Bordro Bilgilerim</h3>

    <table class="table">
        <thead>
            <tr>
                <th>Personel Adı</th>
                <th>Personel Prim/Awards</th>
                <th>PErsonel Maaşı</th>
                <th>Net Ücret</th>
                <th>Bordro Tarihi</th>
                <th>Bordro indir</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.AppUser.FullName</td>
                    <td>@item.Awards</td>
                    <td>@item.AppUser.Salary</td>
                    <td>@(item.Awards + item.AppUser.Salary)</td>
                    <td>@item.CreatedTime</td>
                    <td><a href="@Url.Action("DownloadDataAsPdfID", "PaySlip", new { id = item.Id })" class="btn btn-primary">Bordro İndir</a></td>
                </tr>
            }
        </tbody>
    </table>

</div>

Presentation/Views/PaySlip/UpdatePaySlip.cshtml
@model Entities.Concrete.PaySlip
@{
    ViewData["Title"] = "UpdatePaySlip";
    Layout = "~/Views/Shared/_AdminTemplateLayout.cshtml";
}

<div class="container">
    <h2>Bordro Düzenleme</h2>

    @using (Html.BeginForm())
    {
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.AppUserId, "Personeller")
            @Html.DropDownListFor(model => model.AppUserId, (SelectList)ViewBag.AppUsers, "Personeller", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AppUserId, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Awards)
            @Html.TextBoxFor(model => model.Awards, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Awards, "", new { @class = "text-danger" })
        </div>

        <button type="submit" class="btn btn-info">Değişiklikleri Kaydet</button>
        <a href="/PaySlip/Index" class="btn btn-warning">Değişikliklerden Vazgeç</a>
    }
</div>